// lib/db/index.ts
import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'
import * as schema from './schema'

const connectionString = process.env.DATABASE_URL!

if (!connectionString) {
  throw new Error('DATABASE_URL is not set')
}

const client = postgres(connectionString)
export const db = drizzle(client, { schema })

// Migration file: migrations/0000_initial_schema.sql
// This would be generated by Drizzle Kit